// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: proto/userarmies/armies-service.proto

package userarmies

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserArmyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT        string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	UserArmyId string `protobuf:"bytes,2,opt,name=userArmyId,proto3" json:"userArmyId,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Points     int64  `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *UpdateUserArmyRequest) Reset() {
	*x = UpdateUserArmyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_armies_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserArmyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserArmyRequest) ProtoMessage() {}

func (x *UpdateUserArmyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_armies_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserArmyRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserArmyRequest) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_armies_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserArmyRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *UpdateUserArmyRequest) GetUserArmyId() string {
	if x != nil {
		return x.UserArmyId
	}
	return ""
}

func (x *UpdateUserArmyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserArmyRequest) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

type AddUnitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT        string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	UserArmyId string `protobuf:"bytes,2,opt,name=userArmyId,proto3" json:"userArmyId,omitempty"`
	UnitTypeid string `protobuf:"bytes,3,opt,name=unitTypeid,proto3" json:"unitTypeid,omitempty"`
}

func (x *AddUnitRequest) Reset() {
	*x = AddUnitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_armies_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUnitRequest) ProtoMessage() {}

func (x *AddUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_armies_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUnitRequest.ProtoReflect.Descriptor instead.
func (*AddUnitRequest) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_armies_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddUnitRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *AddUnitRequest) GetUserArmyId() string {
	if x != nil {
		return x.UserArmyId
	}
	return ""
}

func (x *AddUnitRequest) GetUnitTypeid() string {
	if x != nil {
		return x.UnitTypeid
	}
	return ""
}

type RemoveUnitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT        string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	Id         string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	UserArmyId string `protobuf:"bytes,3,opt,name=userArmyId,proto3" json:"userArmyId,omitempty"`
}

func (x *RemoveUnitRequest) Reset() {
	*x = RemoveUnitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_armies_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUnitRequest) ProtoMessage() {}

func (x *RemoveUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_armies_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUnitRequest.ProtoReflect.Descriptor instead.
func (*RemoveUnitRequest) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_armies_service_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveUnitRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *RemoveUnitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveUnitRequest) GetUserArmyId() string {
	if x != nil {
		return x.UserArmyId
	}
	return ""
}

type GetUserArmyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserArmyRequest) Reset() {
	*x = GetUserArmyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_armies_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserArmyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserArmyRequest) ProtoMessage() {}

func (x *GetUserArmyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_armies_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserArmyRequest.ProtoReflect.Descriptor instead.
func (*GetUserArmyRequest) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_armies_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserArmyRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *GetUserArmyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserArmyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserArmy *UserArmy `protobuf:"bytes,1,opt,name=userArmy,proto3" json:"userArmy,omitempty"`
}

func (x *GetUserArmyReply) Reset() {
	*x = GetUserArmyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_armies_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserArmyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserArmyReply) ProtoMessage() {}

func (x *GetUserArmyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_armies_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserArmyReply.ProtoReflect.Descriptor instead.
func (*GetUserArmyReply) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_armies_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserArmyReply) GetUserArmy() *UserArmy {
	if x != nil {
		return x.UserArmy
	}
	return nil
}

type DestroyUserArmyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DestroyUserArmyRequest) Reset() {
	*x = DestroyUserArmyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_armies_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyUserArmyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyUserArmyRequest) ProtoMessage() {}

func (x *DestroyUserArmyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_armies_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyUserArmyRequest.ProtoReflect.Descriptor instead.
func (*DestroyUserArmyRequest) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_armies_service_proto_rawDescGZIP(), []int{5}
}

func (x *DestroyUserArmyRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *DestroyUserArmyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserArmiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT    string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetUserArmiesRequest) Reset() {
	*x = GetUserArmiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_armies_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserArmiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserArmiesRequest) ProtoMessage() {}

func (x *GetUserArmiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_armies_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserArmiesRequest.ProtoReflect.Descriptor instead.
func (*GetUserArmiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_armies_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserArmiesRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *GetUserArmiesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserArmiesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUserArmiesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserArmies []*UserArmy `protobuf:"bytes,1,rep,name=userArmies,proto3" json:"userArmies,omitempty"`
	Count      int64       `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetUserArmiesReply) Reset() {
	*x = GetUserArmiesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_armies_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserArmiesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserArmiesReply) ProtoMessage() {}

func (x *GetUserArmiesReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_armies_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserArmiesReply.ProtoReflect.Descriptor instead.
func (*GetUserArmiesReply) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_armies_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserArmiesReply) GetUserArmies() []*UserArmy {
	if x != nil {
		return x.UserArmies
	}
	return nil
}

func (x *GetUserArmiesReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateUserArmyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT        string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GameId     string `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	ArmyTypeId string `protobuf:"bytes,4,opt,name=armyTypeId,proto3" json:"armyTypeId,omitempty"`
	Points     int64  `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *CreateUserArmyRequest) Reset() {
	*x = CreateUserArmyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_armies_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserArmyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserArmyRequest) ProtoMessage() {}

func (x *CreateUserArmyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_armies_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserArmyRequest.ProtoReflect.Descriptor instead.
func (*CreateUserArmyRequest) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_armies_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateUserArmyRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *CreateUserArmyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserArmyRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CreateUserArmyRequest) GetArmyTypeId() string {
	if x != nil {
		return x.ArmyTypeId
	}
	return ""
}

func (x *CreateUserArmyRequest) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

type CreateUserArmyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserArmy *UserArmy `protobuf:"bytes,1,opt,name=userArmy,proto3" json:"userArmy,omitempty"`
}

func (x *CreateUserArmyReply) Reset() {
	*x = CreateUserArmyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_armies_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserArmyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserArmyReply) ProtoMessage() {}

func (x *CreateUserArmyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_armies_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserArmyReply.ProtoReflect.Descriptor instead.
func (*CreateUserArmyReply) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_armies_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateUserArmyReply) GetUserArmy() *UserArmy {
	if x != nil {
		return x.UserArmy
	}
	return nil
}

type EmptyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_armies_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_armies_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_armies_service_proto_rawDescGZIP(), []int{10}
}

var File_proto_userarmies_armies_service_proto protoreflect.FileDescriptor

var file_proto_userarmies_armies_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69,
	0x65, 0x73, 0x2f, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d,
	0x69, 0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2f, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x4a, 0x57, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x1e,
	0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x62, 0x0a, 0x0e, 0x41, 0x64,
	0x64, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x4a, 0x57, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x1e,
	0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x69, 0x64, 0x22, 0x55,
	0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d,
	0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41,
	0x72, 0x6d, 0x79, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4a,
	0x57, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x30, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x41,
	0x72, 0x6d, 0x79, 0x22, 0x3a, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x4a, 0x57, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4a, 0x57, 0x54, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x56, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x60, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d,
	0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x72, 0x6d, 0x79, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x6d, 0x79, 0x54, 0x79, 0x70, 0x65, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x47, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x30, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x41, 0x72,
	0x6d, 0x79, 0x22, 0x0c, 0x0a, 0x0a, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x32, 0xb8, 0x04, 0x0a, 0x0c, 0x56, 0x31, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x69, 0x65,
	0x73, 0x12, 0x53, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x69,
	0x65, 0x73, 0x12, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x72, 0x6d, 0x79, 0x12, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69,
	0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69,
	0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x12, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72,
	0x6d, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x72, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4f, 0x0a,
	0x0f, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79,
	0x12, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x44, 0x65,
	0x73, 0x74, 0x72, 0x6f, 0x79, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65,
	0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69,
	0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x1d, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x12, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61,
	0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x41, 0x5a, 0x3f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x61, 0x70, 0x70, 0x69, 0x6c,
	0x79, 0x6d, 0x61, 0x72, 0x72, 0x69, 0x65, 0x64, 0x64, 0x61, 0x64, 0x2f, 0x6f, 0x6c, 0x64, 0x2d,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x33, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_userarmies_armies_service_proto_rawDescOnce sync.Once
	file_proto_userarmies_armies_service_proto_rawDescData = file_proto_userarmies_armies_service_proto_rawDesc
)

func file_proto_userarmies_armies_service_proto_rawDescGZIP() []byte {
	file_proto_userarmies_armies_service_proto_rawDescOnce.Do(func() {
		file_proto_userarmies_armies_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_userarmies_armies_service_proto_rawDescData)
	})
	return file_proto_userarmies_armies_service_proto_rawDescData
}

var file_proto_userarmies_armies_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_userarmies_armies_service_proto_goTypes = []interface{}{
	(*UpdateUserArmyRequest)(nil),  // 0: userarmies.UpdateUserArmyRequest
	(*AddUnitRequest)(nil),         // 1: userarmies.AddUnitRequest
	(*RemoveUnitRequest)(nil),      // 2: userarmies.RemoveUnitRequest
	(*GetUserArmyRequest)(nil),     // 3: userarmies.GetUserArmyRequest
	(*GetUserArmyReply)(nil),       // 4: userarmies.GetUserArmyReply
	(*DestroyUserArmyRequest)(nil), // 5: userarmies.DestroyUserArmyRequest
	(*GetUserArmiesRequest)(nil),   // 6: userarmies.GetUserArmiesRequest
	(*GetUserArmiesReply)(nil),     // 7: userarmies.GetUserArmiesReply
	(*CreateUserArmyRequest)(nil),  // 8: userarmies.CreateUserArmyRequest
	(*CreateUserArmyReply)(nil),    // 9: userarmies.CreateUserArmyReply
	(*EmptyReply)(nil),             // 10: userarmies.EmptyReply
	(*UserArmy)(nil),               // 11: userarmies.UserArmy
}
var file_proto_userarmies_armies_service_proto_depIdxs = []int32{
	11, // 0: userarmies.GetUserArmyReply.userArmy:type_name -> userarmies.UserArmy
	11, // 1: userarmies.GetUserArmiesReply.userArmies:type_name -> userarmies.UserArmy
	11, // 2: userarmies.CreateUserArmyReply.userArmy:type_name -> userarmies.UserArmy
	6,  // 3: userarmies.V1UserArmies.GetUserArmies:input_type -> userarmies.GetUserArmiesRequest
	3,  // 4: userarmies.V1UserArmies.GetUserArmy:input_type -> userarmies.GetUserArmyRequest
	8,  // 5: userarmies.V1UserArmies.CreateUserArmy:input_type -> userarmies.CreateUserArmyRequest
	5,  // 6: userarmies.V1UserArmies.DestroyUserArmy:input_type -> userarmies.DestroyUserArmyRequest
	1,  // 7: userarmies.V1UserArmies.AddUnit:input_type -> userarmies.AddUnitRequest
	2,  // 8: userarmies.V1UserArmies.RemoveUnit:input_type -> userarmies.RemoveUnitRequest
	0,  // 9: userarmies.V1UserArmies.UpdateUserArmy:input_type -> userarmies.UpdateUserArmyRequest
	7,  // 10: userarmies.V1UserArmies.GetUserArmies:output_type -> userarmies.GetUserArmiesReply
	4,  // 11: userarmies.V1UserArmies.GetUserArmy:output_type -> userarmies.GetUserArmyReply
	9,  // 12: userarmies.V1UserArmies.CreateUserArmy:output_type -> userarmies.CreateUserArmyReply
	10, // 13: userarmies.V1UserArmies.DestroyUserArmy:output_type -> userarmies.EmptyReply
	10, // 14: userarmies.V1UserArmies.AddUnit:output_type -> userarmies.EmptyReply
	10, // 15: userarmies.V1UserArmies.RemoveUnit:output_type -> userarmies.EmptyReply
	4,  // 16: userarmies.V1UserArmies.UpdateUserArmy:output_type -> userarmies.GetUserArmyReply
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_userarmies_armies_service_proto_init() }
func file_proto_userarmies_armies_service_proto_init() {
	if File_proto_userarmies_armies_service_proto != nil {
		return
	}
	file_proto_userarmies_armies_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_userarmies_armies_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserArmyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_armies_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUnitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_armies_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUnitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_armies_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserArmyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_armies_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserArmyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_armies_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyUserArmyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_armies_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserArmiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_armies_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserArmiesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_armies_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserArmyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_armies_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserArmyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_armies_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_userarmies_armies_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userarmies_armies_service_proto_goTypes,
		DependencyIndexes: file_proto_userarmies_armies_service_proto_depIdxs,
		MessageInfos:      file_proto_userarmies_armies_service_proto_msgTypes,
	}.Build()
	File_proto_userarmies_armies_service_proto = out.File
	file_proto_userarmies_armies_service_proto_rawDesc = nil
	file_proto_userarmies_armies_service_proto_goTypes = nil
	file_proto_userarmies_armies_service_proto_depIdxs = nil
}
