// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: proto/userarmies/units-service.proto

/*
Package userarmies is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package userarmies

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_V1UserArmyUnits_GetUnit_0(ctx context.Context, marshaler runtime.Marshaler, client V1UserArmyUnitsClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetUnitRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.GetUnit(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_V1UserArmyUnits_GetUnit_0(ctx context.Context, marshaler runtime.Marshaler, server V1UserArmyUnitsServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetUnitRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.GetUnit(ctx, &protoReq)
	return msg, metadata, err

}

func request_V1UserArmyUnits_UpdateUnit_0(ctx context.Context, marshaler runtime.Marshaler, client V1UserArmyUnitsClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateUnitRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.UpdateUnit(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_V1UserArmyUnits_UpdateUnit_0(ctx context.Context, marshaler runtime.Marshaler, server V1UserArmyUnitsServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateUnitRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.UpdateUnit(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterV1UserArmyUnitsHandlerServer registers the http handlers for service V1UserArmyUnits to "mux".
// UnaryRPC     :call V1UserArmyUnitsServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterV1UserArmyUnitsHandlerFromEndpoint instead.
func RegisterV1UserArmyUnitsHandlerServer(ctx context.Context, mux *runtime.ServeMux, server V1UserArmyUnitsServer) error {

	mux.Handle("POST", pattern_V1UserArmyUnits_GetUnit_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/userarmies.V1UserArmyUnits/GetUnit", runtime.WithHTTPPathPattern("/userarmies.V1UserArmyUnits/GetUnit"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_V1UserArmyUnits_GetUnit_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_V1UserArmyUnits_GetUnit_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_V1UserArmyUnits_UpdateUnit_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/userarmies.V1UserArmyUnits/UpdateUnit", runtime.WithHTTPPathPattern("/userarmies.V1UserArmyUnits/UpdateUnit"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_V1UserArmyUnits_UpdateUnit_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_V1UserArmyUnits_UpdateUnit_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterV1UserArmyUnitsHandlerFromEndpoint is same as RegisterV1UserArmyUnitsHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterV1UserArmyUnitsHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterV1UserArmyUnitsHandler(ctx, mux, conn)
}

// RegisterV1UserArmyUnitsHandler registers the http handlers for service V1UserArmyUnits to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterV1UserArmyUnitsHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterV1UserArmyUnitsHandlerClient(ctx, mux, NewV1UserArmyUnitsClient(conn))
}

// RegisterV1UserArmyUnitsHandlerClient registers the http handlers for service V1UserArmyUnits
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "V1UserArmyUnitsClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "V1UserArmyUnitsClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "V1UserArmyUnitsClient" to call the correct interceptors.
func RegisterV1UserArmyUnitsHandlerClient(ctx context.Context, mux *runtime.ServeMux, client V1UserArmyUnitsClient) error {

	mux.Handle("POST", pattern_V1UserArmyUnits_GetUnit_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/userarmies.V1UserArmyUnits/GetUnit", runtime.WithHTTPPathPattern("/userarmies.V1UserArmyUnits/GetUnit"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_V1UserArmyUnits_GetUnit_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_V1UserArmyUnits_GetUnit_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_V1UserArmyUnits_UpdateUnit_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/userarmies.V1UserArmyUnits/UpdateUnit", runtime.WithHTTPPathPattern("/userarmies.V1UserArmyUnits/UpdateUnit"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_V1UserArmyUnits_UpdateUnit_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_V1UserArmyUnits_UpdateUnit_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_V1UserArmyUnits_GetUnit_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"userarmies.V1UserArmyUnits", "GetUnit"}, ""))

	pattern_V1UserArmyUnits_UpdateUnit_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"userarmies.V1UserArmyUnits", "UpdateUnit"}, ""))
)

var (
	forward_V1UserArmyUnits_GetUnit_0 = runtime.ForwardResponseMessage

	forward_V1UserArmyUnits_UpdateUnit_0 = runtime.ForwardResponseMessage
)
