// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/userarmies/units-service.proto

package userarmies

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// V1UserArmyUnitsClient is the client API for V1UserArmyUnits service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type V1UserArmyUnitsClient interface {
}

type v1UserArmyUnitsClient struct {
	cc grpc.ClientConnInterface
}

func NewV1UserArmyUnitsClient(cc grpc.ClientConnInterface) V1UserArmyUnitsClient {
	return &v1UserArmyUnitsClient{cc}
}

// V1UserArmyUnitsServer is the server API for V1UserArmyUnits service.
// All implementations must embed UnimplementedV1UserArmyUnitsServer
// for forward compatibility
type V1UserArmyUnitsServer interface {
	mustEmbedUnimplementedV1UserArmyUnitsServer()
}

// UnimplementedV1UserArmyUnitsServer must be embedded to have forward compatible implementations.
type UnimplementedV1UserArmyUnitsServer struct {
}

func (UnimplementedV1UserArmyUnitsServer) mustEmbedUnimplementedV1UserArmyUnitsServer() {}

// UnsafeV1UserArmyUnitsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to V1UserArmyUnitsServer will
// result in compilation errors.
type UnsafeV1UserArmyUnitsServer interface {
	mustEmbedUnimplementedV1UserArmyUnitsServer()
}

func RegisterV1UserArmyUnitsServer(s grpc.ServiceRegistrar, srv V1UserArmyUnitsServer) {
	s.RegisterService(&V1UserArmyUnits_ServiceDesc, srv)
}

// V1UserArmyUnits_ServiceDesc is the grpc.ServiceDesc for V1UserArmyUnits service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var V1UserArmyUnits_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userarmies.V1UserArmyUnits",
	HandlerType: (*V1UserArmyUnitsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/userarmies/units-service.proto",
}
