// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/userarmies/units-service.proto

package userarmies

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	V1UserArmyUnits_GetUnit_FullMethodName    = "/userarmies.V1UserArmyUnits/GetUnit"
	V1UserArmyUnits_UpdateUnit_FullMethodName = "/userarmies.V1UserArmyUnits/UpdateUnit"
)

// V1UserArmyUnitsClient is the client API for V1UserArmyUnits service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type V1UserArmyUnitsClient interface {
	GetUnit(ctx context.Context, in *GetUnitRequest, opts ...grpc.CallOption) (*GetUnitReply, error)
	UpdateUnit(ctx context.Context, in *UpdateUnitRequest, opts ...grpc.CallOption) (*UpdateUnitReply, error)
}

type v1UserArmyUnitsClient struct {
	cc grpc.ClientConnInterface
}

func NewV1UserArmyUnitsClient(cc grpc.ClientConnInterface) V1UserArmyUnitsClient {
	return &v1UserArmyUnitsClient{cc}
}

func (c *v1UserArmyUnitsClient) GetUnit(ctx context.Context, in *GetUnitRequest, opts ...grpc.CallOption) (*GetUnitReply, error) {
	out := new(GetUnitReply)
	err := c.cc.Invoke(ctx, V1UserArmyUnits_GetUnit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v1UserArmyUnitsClient) UpdateUnit(ctx context.Context, in *UpdateUnitRequest, opts ...grpc.CallOption) (*UpdateUnitReply, error) {
	out := new(UpdateUnitReply)
	err := c.cc.Invoke(ctx, V1UserArmyUnits_UpdateUnit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// V1UserArmyUnitsServer is the server API for V1UserArmyUnits service.
// All implementations must embed UnimplementedV1UserArmyUnitsServer
// for forward compatibility
type V1UserArmyUnitsServer interface {
	GetUnit(context.Context, *GetUnitRequest) (*GetUnitReply, error)
	UpdateUnit(context.Context, *UpdateUnitRequest) (*UpdateUnitReply, error)
	mustEmbedUnimplementedV1UserArmyUnitsServer()
}

// UnimplementedV1UserArmyUnitsServer must be embedded to have forward compatible implementations.
type UnimplementedV1UserArmyUnitsServer struct {
}

func (UnimplementedV1UserArmyUnitsServer) GetUnit(context.Context, *GetUnitRequest) (*GetUnitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnit not implemented")
}
func (UnimplementedV1UserArmyUnitsServer) UpdateUnit(context.Context, *UpdateUnitRequest) (*UpdateUnitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUnit not implemented")
}
func (UnimplementedV1UserArmyUnitsServer) mustEmbedUnimplementedV1UserArmyUnitsServer() {}

// UnsafeV1UserArmyUnitsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to V1UserArmyUnitsServer will
// result in compilation errors.
type UnsafeV1UserArmyUnitsServer interface {
	mustEmbedUnimplementedV1UserArmyUnitsServer()
}

func RegisterV1UserArmyUnitsServer(s grpc.ServiceRegistrar, srv V1UserArmyUnitsServer) {
	s.RegisterService(&V1UserArmyUnits_ServiceDesc, srv)
}

func _V1UserArmyUnits_GetUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1UserArmyUnitsServer).GetUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V1UserArmyUnits_GetUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1UserArmyUnitsServer).GetUnit(ctx, req.(*GetUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V1UserArmyUnits_UpdateUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1UserArmyUnitsServer).UpdateUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V1UserArmyUnits_UpdateUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1UserArmyUnitsServer).UpdateUnit(ctx, req.(*UpdateUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// V1UserArmyUnits_ServiceDesc is the grpc.ServiceDesc for V1UserArmyUnits service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var V1UserArmyUnits_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userarmies.V1UserArmyUnits",
	HandlerType: (*V1UserArmyUnitsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUnit",
			Handler:    _V1UserArmyUnits_GetUnit_Handler,
		},
		{
			MethodName: "UpdateUnit",
			Handler:    _V1UserArmyUnits_UpdateUnit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/userarmies/units-service.proto",
}
