// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: proto/userarmies/units-service.proto

package userarmies

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUnitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUnitRequest) Reset() {
	*x = GetUnitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_units_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnitRequest) ProtoMessage() {}

func (x *GetUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_units_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnitRequest.ProtoReflect.Descriptor instead.
func (*GetUnitRequest) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_units_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUnitRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *GetUnitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUnitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit *ArmyUnit `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *GetUnitReply) Reset() {
	*x = GetUnitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_units_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnitReply) ProtoMessage() {}

func (x *GetUnitReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_units_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnitReply.ProtoReflect.Descriptor instead.
func (*GetUnitReply) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_units_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUnitReply) GetUnit() *ArmyUnit {
	if x != nil {
		return x.Unit
	}
	return nil
}

type UpdateUserArmyUnitOptionValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsSelected    bool     `protobuf:"varint,2,opt,name=is_selected,json=isSelected,proto3" json:"is_selected,omitempty"`
	IndexSelected string   `protobuf:"bytes,3,opt,name=index_selected,json=indexSelected,proto3" json:"index_selected,omitempty"`
	IdsSelected   []string `protobuf:"bytes,4,rep,name=ids_selected,json=idsSelected,proto3" json:"ids_selected,omitempty"`
	QtySelected   int64    `protobuf:"varint,5,opt,name=qty_selected,json=qtySelected,proto3" json:"qty_selected,omitempty"`
}

func (x *UpdateUserArmyUnitOptionValue) Reset() {
	*x = UpdateUserArmyUnitOptionValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_units_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserArmyUnitOptionValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserArmyUnitOptionValue) ProtoMessage() {}

func (x *UpdateUserArmyUnitOptionValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_units_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserArmyUnitOptionValue.ProtoReflect.Descriptor instead.
func (*UpdateUserArmyUnitOptionValue) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_units_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserArmyUnitOptionValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserArmyUnitOptionValue) GetIsSelected() bool {
	if x != nil {
		return x.IsSelected
	}
	return false
}

func (x *UpdateUserArmyUnitOptionValue) GetIndexSelected() string {
	if x != nil {
		return x.IndexSelected
	}
	return ""
}

func (x *UpdateUserArmyUnitOptionValue) GetIdsSelected() []string {
	if x != nil {
		return x.IdsSelected
	}
	return nil
}

func (x *UpdateUserArmyUnitOptionValue) GetQtySelected() int64 {
	if x != nil {
		return x.QtySelected
	}
	return 0
}

type UpdateUserArmyUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Qty:
	//
	//	*UpdateUserArmyUnit_QtyNull
	//	*UpdateUserArmyUnit_QtyValue
	Qty          isUpdateUserArmyUnit_Qty         `protobuf_oneof:"qty"`
	OptionValues []*UpdateUserArmyUnitOptionValue `protobuf:"bytes,4,rep,name=option_values,json=optionValues,proto3" json:"option_values,omitempty"`
	Points       int64                            `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *UpdateUserArmyUnit) Reset() {
	*x = UpdateUserArmyUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_units_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserArmyUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserArmyUnit) ProtoMessage() {}

func (x *UpdateUserArmyUnit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_units_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserArmyUnit.ProtoReflect.Descriptor instead.
func (*UpdateUserArmyUnit) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_units_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserArmyUnit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (m *UpdateUserArmyUnit) GetQty() isUpdateUserArmyUnit_Qty {
	if m != nil {
		return m.Qty
	}
	return nil
}

func (x *UpdateUserArmyUnit) GetQtyNull() bool {
	if x, ok := x.GetQty().(*UpdateUserArmyUnit_QtyNull); ok {
		return x.QtyNull
	}
	return false
}

func (x *UpdateUserArmyUnit) GetQtyValue() int64 {
	if x, ok := x.GetQty().(*UpdateUserArmyUnit_QtyValue); ok {
		return x.QtyValue
	}
	return 0
}

func (x *UpdateUserArmyUnit) GetOptionValues() []*UpdateUserArmyUnitOptionValue {
	if x != nil {
		return x.OptionValues
	}
	return nil
}

func (x *UpdateUserArmyUnit) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

type isUpdateUserArmyUnit_Qty interface {
	isUpdateUserArmyUnit_Qty()
}

type UpdateUserArmyUnit_QtyNull struct {
	QtyNull bool `protobuf:"varint,2,opt,name=qty_null,json=qtyNull,proto3,oneof"`
}

type UpdateUserArmyUnit_QtyValue struct {
	QtyValue int64 `protobuf:"varint,3,opt,name=qty_value,json=qtyValue,proto3,oneof"`
}

func (*UpdateUserArmyUnit_QtyNull) isUpdateUserArmyUnit_Qty() {}

func (*UpdateUserArmyUnit_QtyValue) isUpdateUserArmyUnit_Qty() {}

type UpdateUnitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT            string              `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	UpdateArmyUnit *UpdateUserArmyUnit `protobuf:"bytes,2,opt,name=update_army_unit,json=updateArmyUnit,proto3" json:"update_army_unit,omitempty"`
}

func (x *UpdateUnitRequest) Reset() {
	*x = UpdateUnitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_units_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUnitRequest) ProtoMessage() {}

func (x *UpdateUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_units_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUnitRequest.ProtoReflect.Descriptor instead.
func (*UpdateUnitRequest) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_units_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUnitRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *UpdateUnitRequest) GetUpdateArmyUnit() *UpdateUserArmyUnit {
	if x != nil {
		return x.UpdateArmyUnit
	}
	return nil
}

type UpdateUnitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateUnitReply) Reset() {
	*x = UpdateUnitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userarmies_units_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUnitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUnitReply) ProtoMessage() {}

func (x *UpdateUnitReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userarmies_units_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUnitReply.ProtoReflect.Descriptor instead.
func (*UpdateUnitReply) Descriptor() ([]byte, []int) {
	return file_proto_userarmies_units_service_proto_rawDescGZIP(), []int{5}
}

var File_proto_userarmies_units_service_proto protoreflect.FileDescriptor

var file_proto_userarmies_units_service_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69,
	0x65, 0x73, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69,
	0x65, 0x73, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72,
	0x6d, 0x69, 0x65, 0x73, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x32, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4a, 0x57, 0x54, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e,
	0x41, 0x72, 0x6d, 0x79, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0xbd,
	0x01, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d,
	0x79, 0x55, 0x6e, 0x69, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x64, 0x73, 0x5f,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x69, 0x64, 0x73, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x71,
	0x74, 0x79, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x71, 0x74, 0x79, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0xcf,
	0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d,
	0x79, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x08, 0x71, 0x74, 0x79, 0x5f, 0x6e, 0x75, 0x6c,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x71, 0x74, 0x79, 0x4e, 0x75,
	0x6c, 0x6c, 0x12, 0x1d, 0x0a, 0x09, 0x71, 0x74, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x71, 0x74, 0x79, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61,
	0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x72, 0x6d, 0x79, 0x55, 0x6e, 0x69, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x71, 0x74, 0x79,
	0x22, 0x6f, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x48, 0x0a, 0x10, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x61, 0x72, 0x6d, 0x79, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x79, 0x55, 0x6e, 0x69,
	0x74, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x6d, 0x79, 0x55, 0x6e, 0x69,
	0x74, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0xa0, 0x01, 0x0a, 0x0f, 0x56, 0x31, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x72, 0x6d, 0x79, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x41, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55,
	0x6e, 0x69, 0x74, 0x12, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61,
	0x72, 0x6d, 0x69, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x61, 0x70, 0x70, 0x69, 0x6c, 0x79, 0x6d, 0x61, 0x72,
	0x72, 0x69, 0x65, 0x64, 0x64, 0x61, 0x64, 0x2f, 0x6f, 0x6c, 0x64, 0x2d, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2f, 0x61, 0x70, 0x69, 0x33, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x61, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_userarmies_units_service_proto_rawDescOnce sync.Once
	file_proto_userarmies_units_service_proto_rawDescData = file_proto_userarmies_units_service_proto_rawDesc
)

func file_proto_userarmies_units_service_proto_rawDescGZIP() []byte {
	file_proto_userarmies_units_service_proto_rawDescOnce.Do(func() {
		file_proto_userarmies_units_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_userarmies_units_service_proto_rawDescData)
	})
	return file_proto_userarmies_units_service_proto_rawDescData
}

var file_proto_userarmies_units_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_userarmies_units_service_proto_goTypes = []interface{}{
	(*GetUnitRequest)(nil),                // 0: userarmies.GetUnitRequest
	(*GetUnitReply)(nil),                  // 1: userarmies.GetUnitReply
	(*UpdateUserArmyUnitOptionValue)(nil), // 2: userarmies.UpdateUserArmyUnitOptionValue
	(*UpdateUserArmyUnit)(nil),            // 3: userarmies.UpdateUserArmyUnit
	(*UpdateUnitRequest)(nil),             // 4: userarmies.UpdateUnitRequest
	(*UpdateUnitReply)(nil),               // 5: userarmies.UpdateUnitReply
	(*ArmyUnit)(nil),                      // 6: userarmies.ArmyUnit
}
var file_proto_userarmies_units_service_proto_depIdxs = []int32{
	6, // 0: userarmies.GetUnitReply.unit:type_name -> userarmies.ArmyUnit
	2, // 1: userarmies.UpdateUserArmyUnit.option_values:type_name -> userarmies.UpdateUserArmyUnitOptionValue
	3, // 2: userarmies.UpdateUnitRequest.update_army_unit:type_name -> userarmies.UpdateUserArmyUnit
	0, // 3: userarmies.V1UserArmyUnits.GetUnit:input_type -> userarmies.GetUnitRequest
	4, // 4: userarmies.V1UserArmyUnits.UpdateUnit:input_type -> userarmies.UpdateUnitRequest
	1, // 5: userarmies.V1UserArmyUnits.GetUnit:output_type -> userarmies.GetUnitReply
	5, // 6: userarmies.V1UserArmyUnits.UpdateUnit:output_type -> userarmies.UpdateUnitReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_userarmies_units_service_proto_init() }
func file_proto_userarmies_units_service_proto_init() {
	if File_proto_userarmies_units_service_proto != nil {
		return
	}
	file_proto_userarmies_units_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_userarmies_units_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_units_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_units_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserArmyUnitOptionValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_units_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserArmyUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_units_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUnitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userarmies_units_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUnitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_userarmies_units_service_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*UpdateUserArmyUnit_QtyNull)(nil),
		(*UpdateUserArmyUnit_QtyValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_userarmies_units_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userarmies_units_service_proto_goTypes,
		DependencyIndexes: file_proto_userarmies_units_service_proto_depIdxs,
		MessageInfos:      file_proto_userarmies_units_service_proto_msgTypes,
	}.Build()
	File_proto_userarmies_units_service_proto = out.File
	file_proto_userarmies_units_service_proto_rawDesc = nil
	file_proto_userarmies_units_service_proto_goTypes = nil
	file_proto_userarmies_units_service_proto_depIdxs = nil
}
